version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
  open-pull-requests-limit: 1
  groups:
    k8s:
      applies-to: version-updates
      patterns:
      - "k8s.io*"
      update-types:
      - "patch"
      - "minor"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
  open-pull-requests-limit: 1
- package-ecosystem: "docker"
  directory: "/pkg/blobplugin/"
  schedule:
    interval: "daily"
    time: "01:00"
    timezone: "Asia/Shanghai"
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
    - "kind/cleanup"
