---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-keyvault
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse
  csi:
    driver: blob.csi.azure.com
    # make sure volumeid is unique for every storage blob container in the cluster
    volumeHandle: account-name_container-name
    volumeAttributes:
      containerName: EXISTING_CONTAINER_NAME
      storageAccountName: EXISTING_STORAGE_ACCOUNT_NAME
      keyVaultURL: https://xxx.vault.azure.net/
      keyVaultSecretName: xxx
